# WebSocket Event Definitions

# Client -> Server
EVENT_AGENT_REGISTER = "AGENT_REGISTER"
EVENT_AGENT_HEARTBEAT = "AGENT_HEARTBEAT"
EVENT_AGENT_TELEMETRY = "AGENT_TELEMETRY"
EVENT_AGENT_COMMAND_RESULT = "AGENT_COMMAND_RESULT"
EVENT_PORTAL_SUBSCRIBE = "PORTAL_SUBSCRIBE"
EVENT_PORTAL_UNSUBSCRIBE = "PORTAL_UNSUBSCRIBE"

# Server -> Client / Portal Broadcast
EVENT_DEVICE_REGISTERED = "DEVICE_REGISTERED"
EVENT_DEVICE_ONLINE = "DEVICE_ONLINE"
EVENT_DEVICE_OFFLINE = "DEVICE_OFFLINE"
EVENT_DEVICE_STALE = "DEVICE_STALE"
EVENT_HEARTBEAT_RECEIVED = "HEARTBEAT_RECEIVED"
EVENT_AGENT_VERSION_CHANGED = "AGENT_VERSION_CHANGED"
EVENT_DEVICE_STATUS_CHANGED = "DEVICE_STATUS_CHANGED"

EVENT_AGENT_HEARTBEAT_ACK = "AGENT_HEARTBEAT_ACK"
EVENT_ALERT_TRIGGERED = "ALERT_TRIGGERED"
EVENT_ALERT_RESOLVED = "ALERT_RESOLVED"
EVENT_COMMAND_DISPATCHED = "COMMAND_DISPATCHED"
EVENT_COMMAND_STATUS_UPDATED = "COMMAND_STATUS_UPDATED"
EVENT_WORK_SESSION_UPDATED = "WORK_SESSION_UPDATED"
EVENT_CONFIGURATION_UPDATED = "CONFIGURATION_UPDATED"
EVENT_EVENT_RECORDED = "EVENT_RECORDED"
