export const WS_EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  PORTAL_SUBSCRIBE: 'PORTAL_SUBSCRIBE',
  PORTAL_UNSUBSCRIBE: 'PORTAL_UNSUBSCRIBE',
  
  // Device & Agent Events
  DEVICE_REGISTERED: 'DEVICE_REGISTERED',
  DEVICE_ONLINE: 'DEVICE_ONLINE',
  DEVICE_OFFLINE: 'DEVICE_OFFLINE',
  DEVICE_STALE: 'DEVICE_STALE',
  HEARTBEAT_RECEIVED: 'HEARTBEAT_RECEIVED',
  AGENT_VERSION_CHANGED: 'AGENT_VERSION_CHANGED',
  DEVICE_STATUS_CHANGED: 'DEVICE_STATUS_CHANGED',

  // Monitoring & Alerts
  ALERT_TRIGGERED: 'ALERT_TRIGGERED',
  ALERT_RESOLVED: 'ALERT_RESOLVED',
  COMMAND_STATUS_UPDATED: 'COMMAND_STATUS_UPDATED',
  CONFIGURATION_UPDATED: 'CONFIGURATION_UPDATED',
  EVENT_RECORDED: 'EVENT_RECORDED',
  WORK_SESSION_UPDATED: 'WORK_SESSION_UPDATED',
} as const;
